### PR TITLE
feat: include paragon in atlas pull as well

### PR DESCRIPTION
**Pull request by OmarIthawi**
This is a follow up to https://github.com/openedx/frontend-template-application/pull/612 . #612 should have included the changes but apparently OEP-58 needs more publicity.

Testing
--------

I've ran the following:

```
$ OPENEDX_ATLAS_PULL=yes make pull_translations
$ cat src/i18n/index.js
```

Generates the following code, which seems to be good:

```js
// This file is generated by the openedx/frontend-platform's "intl-import.js" script.
//
// Refer to the i18n documents in https://docs.openedx.org/en/latest/developers/references/i18n.html to update
// the file and use the Micro-frontend i18n pattern in new repositories.
//

import messagesFromParagon from './messages/paragon';
import messagesFromFrontendComponentHeader from './messages/frontend-component-header';
import messagesFromFrontendComponentFooter from './messages/frontend-component-footer';
// Skipped import due to missing 'frontend-template-application/index.js' likely due to empty translations..

export default [
  messagesFromParagon,
  messagesFromFrontendComponentHeader,
  messagesFromFrontendComponentFooter,
];
```

References
----------

This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Up-to-date project overview and details are available in the [Approach Memo and Technical Discovery: Translations Infrastructure Implementation](https://docs.google.com/document/d/11dFBCnbdHiCEdZp3pZeHdeH8m7Glla-XbIin7cnIOzU/edit#) document.

Join the conversation on [Open edX Slack #translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T).

Check the links above for full information about the overall project.

Internalization is being rearchitected in Open edX Python, XBlock, Micro-frontend, and other projects. There are a number of immediately visible changes:
 - Remove source and language translations from the repositories, hence no `.json`, `.po` or `.mo` files will be committed into the repos.
 - Add standardized `make extract_translations` in all repositories
 - Push user-facing messages strings into [openedx/openedx-translations](https://github.com/openedx/openedx-translations/).
 - Integrate root repositories with [openedx/openedx-atlas](https://github.com/openedx/openedx-atlas/) to pull translations on build/deploy time

Breaking Changes
----------------

One of the primary goals of the project is to **avoid breaking changes**. If you noticed any suspicious code, please raise your concern. But before that, please know the strategy we're following to avoid breaking changes:

**For Micro-frontends:**

 - Legacy hardcoded translations are kept into the repo.
 - Consolidate all i18n imports into `src/i18n/index.js`
 - Add `atlas` integration in `make pull_translations` but only if `OPENEDX_ATLAS_PULL` is set
 - Bump frontend-platform and use `intl-imports.js` to generate up to date import files
 - If translations is missing, they're added according to the latest Micro-frontend i18n pattern in par with https://github.com/openedx/frontend-template-application/

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by openedx-webhooks** [comment]
@OmarIthawi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-template-application&entry.867055334=https://github.com/openedx/frontend-template-application/pull/622&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2023-07-22+15:38&entry.1917517419=2023-07-22+17:32&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by adamstankiewicz** [comment]
> Bump frontend-platform and use intl-imports.js to generate up to date import files

@OmarIthawi It might helpful to edit the instructions to indicate the minimum version of frontend-platform consumers need for using intl-imports.js, perhaps with a link to its release notes.

**Comment by OmarIthawi** [comment]
> > Bump frontend-platform and use intl-imports.js to generate up to date import files
> 
> @OmarIthawi It might helpful to edit the instructions to indicate the minimum version of frontend-platform consumers need for using intl-imports.js, perhaps with a link to its release notes.

Good catch @adamstankiewicz , I've [already gone through all MFEs and updated them](https://docs.google.com/spreadsheets/d/1zLs5pui27rqVC3IV30ZM1_6WP7rE55TyN1ECT3myHTk/edit#gid=0). This line should be removed from my pull request templates.

As you probably guess, this template is copied to provide as much information as possible for anyone reviewing the PRs related to OEP-58.

**Comment by adamstankiewicz** [comment]
@OmarIthawi Got it! Just a heads up, don't have access to the link you shared 😀 thanks for the clarification.

**Comment by OmarIthawi** [comment]
> @OmarIthawi Got it! Just a heads up, I don't have access to the link you shared grinning thanks for the clarification.

Sorry, I've added you now.

**Pull request merged**
